### PR TITLE
lab 2 suggestions

### PR DESCRIPTION
**Pull request by phanaq**
#25 

done reviewing, looks good to me.
only question is - what is the "easy way to mess this up" that you are referring to in the last part of the challenge problem?

### CODE REVIEW

**Comment by anisfeld** [comment]
@phanaq Do you have any suggestions as to how to make the last part clearer for students or other TAs?

**Comment by anisfeld** [comment]
Also @phanaq  instead of using colab, we'll recommend rstudio cloud. Can you adjust that please?

"If you find yourself in lab without R installed, try using RStudio cloud [https://rstudio.cloud/]( https://rstudio.cloud/).^[Sign up for the free tier which should be sufficient for camp. You will have to install packages.]"

**Comment by phanaq** [comment]
@anisfeld done, lmk if there's anything else i should change!

**Comment by anisfeld** [comment]
Great. This address #25

**Pull request merged**
